version: "2.1"
services:
  composer:
    image: composer
    volumes:
      - ./:/app
  app:
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=laravel.dev
    links:
      - mysql:mysqlhost
    ports:
      - 0:80
    network_mode: bridge
  mysql:
    image: mysql
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuserpass
      - MYSQL_ROOT_PASSWORD=mypass
    network_mode: bridge